---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Home Server Enviorment"
subtitle: "Branconet"
logo: "assets/branconet_assets/coffe.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
# message:
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Welcome to Branconet!"
#   icon: "fa fa-grin"
#   content: "This is the homepage for branconet's home enviorment. <br /> Find more information on customizing homer <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
#   - name: "Contribute"
#     icon: "fab fa-github"
#     url: "https://github.com/bastienwirtz/homer"
#     target: "_blank" # optional html a tag target attribute
#   - name: "Wiki"
#     icon: "fas fa-book"
#     url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "JTMB Github"
    icon: "fab fa-github"
    url: "https://github.com/jtmb/raspberrypi-dev-setup"

  - name: "Help Wiki"
    icon: "fas fa-question"
    url: "https://github.com/bastienwirtz/homer#getting-started"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-chevron-right"
    items:
      - name: "PiHole"
        logo: "assets/branconet_assets/pihole.png"
        subtitle: "PiHole hosted on PI"
        tag: "app"
        url: "http://pihole.box:8091/admin/"
        target: "_blank" # optional html a tag target attribute

      - name: "Portainer"
        logo: "assets/branconet_assets/portainer.png"
        subtitle: "Protainer hosted on PI"
        tag: "app"
        url: "http://portainer.box:8090/"

      - name: "Jenkins"
        logo: "assets/branconet_assets/jenkins.png"
        subtitle: "Jenkins hosted on MINI"
        tag: "app"
        url: "http://jenkins.box:8091/"


  - name: "Monitoring"
    icon: "fab fa-watchman-monitoring"
    items:
      - name: "Glances Mini"
        logo: "assets/branconet_assets/glances.png"
        subtitle: "Glances hosted on MINI"
        tag: "Monitoring"
        url: "http://192.168.0.21:8093/"
    
      - name: "Glances PI"
        logo: "assets/branconet_assets/glances.png"
        subtitle: "Glances hosted on PI"
        tag: "Monitoring"
        url: "http://192.168.0.19:8093/"

      - name: "Glances MEDIA"
        logo: "assets/branconet_assets/glances.png"
        subtitle: "Glances hosted on MEDIA"
        tag: "Monitoring"
        url: "http://192.168.0.23:8093/"


  - name: "Storage and Media"
    icon: "fas fa-hdd"
    items:
      - name: "trueNAS"
        logo: "assets/branconet_assets/truenas.png"
        subtitle: "trueNAS OS"
        tag: "Storage"
        url: "http://truenas.home/"
    
      - name: "Plex"
        logo: "assets/branconet_assets/plex.png"
        subtitle: "Plex hosted on MEDIA"
        tag: "Media"
        url: "http://192.168.0.23:32400/manage"

      - name: "Next Cloud"
        logo: "assets/branconet_assets/nextcloud.png"
        subtitle: "NextCloud hosted on MEDIA"
        tag: "Media"
        url: "http://nextcloud.box"


  - name: "Web Servers"
    icon: "fas fa-cloud"
    items:
      - name: "Reverse Proxy"
        logo: "assets/branconet_assets/nginx.png"
        subtitle: "WebServer hosted on PI"
        tag: "web"
        url: "http://192.168.0.19/"
    
      - name: "lucinda.branconet.com"
        logo: "assets/branconet_assets/nginx.png"
        subtitle: "WebServer hosted on PI"
        tag: "web"
        url: "http://192.168.0.19:8080/"

      - name: "santos.branconet.com"
        logo: "assets/branconet_assets/nginx.png"
        subtitle: "WebServer hosted on PI"
        tag: "web"
        url: "http://192.168.0.19:8081/"

  - name: "Utilities"
    icon: "fas fa-wrench"
    items:
      - name: "File Browser"
        logo: "assets/branconet_assets/filebrowser.png"
        subtitle: "File Browser hosted on MEDIA"
        tag: "ftp"
        url: "http://files.box:8092/"